spring:
  profiles: eureka1
  application:
      name: eureka-server
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/
  server:
    enableSelfPreservation: false #关闭自我保护模式
    eviction-interval-timer-in-ms: 5000 #5秒清理一次注册表
---
spring:
  profiles: eureka2
  application:
        name: eureka-server
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka2:8762/eureka/
  server:
    enableSelfPreservation: false #关闭自我保护模式
    eviction-interval-timer-in-ms: 5000 #5秒清理一次注册表