server:
  port: 9000
spring:
  application:
    name: eureka-zuul-server
zuul:
  routes:
    invoke:
      path: /invoke/**
      serviceId: eureka-client-invoke
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5 #5秒发送一次心跳给eureka服务器
    leaseExpirationDurationInSeconds: 10 #10秒接收不到心跳把服务断开
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
    instanceInfoReplicationIntervalSeconds: 10 #10秒发送一次服务状态给eureka服务器(用于actuator健康检查)